### ISSUE TITLE
Channels Not Working 

### ISSUE THREAD

**Issue by weldon1045** [luongz/iptv-jp#109]
It seems most of the Primehome channels, plus partially some Vthanh channels are currently not working.

Primehome is returning Error 403, While with Vthanh channels there is Error 404. It's unsure whether the issue with Primehome will persist or not.

**Comment by weldon1045** [comment]
By the way, it seems the Neetball website was taken down and that source is not working anymore.

**Comment by luongz** [comment]
VThanh channels are still working on my side. And the PrimeHome links are tokenized,  I can't do anything for this, so I decided to take down the PrimeHome links.

**Comment by weldon1045** [comment]
All Vthanh channels seem to be down again, please check.

**Comment by bigloubeats** [comment]
Yep most channels seem to be down atm.

**Comment by luongz** [comment]
I have asked Thanh about it,wait for reponse.

**Comment by luongz** [comment]
VThanh links will back soon. (~1-3 hours.)

**Comment by That1neSGuy5291** [comment]
It seems like the primehome and the vnpt.nekocdn.xyz always goes down at random intervals for absolutely no reason at all. From what I've seen only the test ones works most of the time.

**Comment by That1neSGuy5291** [comment]
By using an O11 streamer the vnpt links shows 'Error: HTTP Get returned status code 404' while the primehome ones shows 'Error: TS failed getting quality manifest for [resolution (bitrate Kb/s)] error [HTTP Get returned status code 403]', although the NHK ones for vnpt are working now.

**Comment by luongz** [comment]
> By using an O11 streamer the vnpt links shows 'Error: HTTP Get returned status code 404' while the primehome ones shows 'Error: TS failed getting quality manifest for [resolution (bitrate Kb/s)] error [HTTP Get returned status code 403]', although the NHK ones for vnpt are working now.

I don't face any of the problems that you mentioned. (tested in PotPlayer/VLC)

**Comment by dm-25** [comment]
tokyo mx1test   NHK-g testが映りません。お時間が有れば直してください
