### ISSUE TITLE
channelは見られません

### ISSUE THREAD

**Issue by bosh-bos** [luongz/iptv-jp#121]
TBS 見られませんですけど、お願いいたします🙇

**Comment by luongz** [comment]
Server maintenance, maybe 6pm GMT +7 it will be back.

**Comment by bosh-bos** [comment]
ummm.. I think it's still not working though~ Could you please fix that ?
Thank you so much in advance :)

**Comment by luongz** [comment]
Thanh managed the TBS link so we need to wait.

**Comment by bosh-bos** [comment]
OK thank you :D

**Comment by luongz** [comment]
Hello, please check again, the TBS channel.

**Comment by luongz** [comment]
I can confirm that both server are working now.
