### ISSUE TITLE
Channel Issue 

### ISSUE THREAD

**Issue by weldon1045** [luongz/iptv-jp#123]
It seems that Tokyo MX1 url is actually hosting BS11 stream, while the BS11 url returns Error 404.

Test MX2 seems to be down as well.

**Comment by luongz** [comment]
> It seems that Tokyo MX1 url is actually hosting BS11 stream, while the BS11 url returns Error 404.

Need to wait for Thanh reponse.

> Test MX2 seems to be down as well.

No signal right now :)
