### ISSUE TITLE
All vthanh streams are down again

### ISSUE THREAD

**Issue by DimitarCC** [luongz/iptv-jp#125]
Well all vthanh streams are down now.....

![image](https://github.com/user-attachments/assets/51fdd3bc-0716-4c48-8670-0922fd8aa1b6)

**Comment by luongz** [comment]
We moved to a new hosting provider, so maybe take a long time...

**Comment by snivy21** [comment]
> We moved to a new hosting provider, so maybe take a long time...

Can you have any alternative right now?

**Comment by luongz** [comment]
No

**Comment by d46544n** [comment]
some willfon streams (eg テレ東: https://stream01.willfonk.com/live_playlist.m3u8?cid=BS297&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1) are working right now, though it lags a bit

**Comment by snivy21** [comment]
> some willfon streams (eg テレ東: https://stream01.willfonk.com/live_playlist.m3u8?cid=BS297&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1) are working right now, though it lags a bit

I have this lol already..it lags too much xd honestly I really liked the vthanh source because it worked smooth

**Comment by DimitarCC** [comment]
To be honest Vthanh streams was stable and smooth indeed. But what i dont really like is that constant hosting switching and moving around that makes the streams gone for days.... :(

As for willfonk links...Yes they shutter a lot depending on your location...

**Comment by snivy21** [comment]
> To be honest Vthanh streams was stable and smooth indeed. But what i dont really like is that constant hosting switching and moving around that makes the streams gone for days.... :(
> 
> As for willfonk links...Yes they shutter a lot depending on your location...

Fr man...I am not complaining but ngl they have to make it permanent host rather than switching 

Also do you know what location is best to run willfonk links without any issue? If there is I'll switch the location through vpn

**Comment by DimitarCC** [comment]
Well i am not sure where is best to watch them but i watch them from east Europe and if i open it in VLC it shutter a lot...
However if i pass them through ffmpeg and stream them to VLC it do shutter a bit at beginning and then is pretty watchable...
So maybe the player do matters as well...

**Comment by snivy21** [comment]
> Well i am not sure where is best to watch them but i watch them from east Europe and if i open it in VLC it shutter a lot... However if i pass them through ffmpeg and stream them to VLC it do shutter a bit at beginning and then is pretty watchable... So maybe the player do matters as well...

I see! Alright

**Comment by luongz** [comment]
Update your playlist. Since Thanh is very busy IRL, this is what I can do now.
The stream may be down.

**Comment by snivy21** [comment]
> Update your playlist. Since Thanh is very busy IRL, this is what I can do now. The stream may be down.

How to do that? Any tutorial please

**Comment by weldon1045** [comment]
If your client is VLC on PC, you just have to open the link and do nothing else.

If you have any other client like Tivimate and such, there it should.be an option to update the list, but it pretty much depends on what are you running the streams on right now.

**Comment by JapanIPTVfan** [comment]
> Well i am not sure where is best to watch them but i watch them from east Europe and if i open it in VLC it shutter a lot... However if i pass them through ffmpeg and stream them to VLC it do shutter a bit at beginning and then is pretty watchable... So maybe the player do matters as well...

@DimitarCC may I ask how you pass through ffmeg and stream to VLC ?

**Comment by dm-25** [comment]
地上波・BS・CSの追加予定有りますか？

**Comment by weldon1045** [comment]
Not anytime soon it seems
