### ISSUE TITLE
Help with buffering?

### ISSUE THREAD

**Issue by kaumac** [luongz/iptv-jp#127]
Hi guys, first of all thanks for maintaining this!

I'm new to the whole iptv/m3u streaming. I'm trying to setup Japanese channels for my grandmother (Japanese) here in Brazil and it's very hard because everything is geoblocked.

And then I found this repo, installed Tivimate and the experience is pretty good! 

The only problem is the all channels seem to buffer a lot (like 10 seconds buffer for 5 seconds playing).
I know this is probably a newbie question, but is there a way to improve the buffering? Would a VPN make it faster? Or is this a limitation of the streaming provider?

Thanks again for the work!

**Comment by luongz** [comment]
Our server is located in Singapore. It is halfway around the world from Brazil.

VPN doesn't help faster. Check your network quality, or set the buffer time longer (idk how to explain it, i will check it later)
