### ISSUE TITLE
Vthanh server is unwatchable

### ISSUE THREAD

**Issue by DimitarCC** [luongz/iptv-jp#137]
Vthanh server is unwatchable. Streams doesn't start or if they start they shutter a lot and stop after few seconds.
Looks like bandwidth issues again....
Can you fix that please?
Thanks!

**Comment by DimitarCC** [comment]
Well it is broken again....
I believe test channels you provide are with much better stability :(

**Comment by luongz** [comment]
We don't have high bandwidth server so can't fix.

**Comment by DimitarCC** [comment]
But your test channels perform much better...Is that on another server?

**Comment by luongz** [comment]
> But your test channels perform much better...Is that on another server?

Yes

**Comment by DimitarCC** [comment]
OK. I understand.... Then can you provide more test channels since they work much more stable on your test servers?

**Comment by luongz** [comment]
> OK. I understand.... Then can you provide more test channels since they work much more stable on your test servers?

Nah, i can't
