### ISSUE TITLE
Request to add a channel

### ISSUE THREAD

**Issue by nazonomi** [luongz/iptv-jp#20]
Add a channel called Sun-TV(kansai).

Or please correct this link.

http://rip.hidari.moe/get/jptv/get.php?id=E7fZyuqrQ657ODVKC1Wj7g==

**Comment by luongz** [comment]
"Sometimes links reponsed can't play , try play again"

Vào Th 3, 9 thg 5, 2023 lúc 16:35 nazonomi ***@***.***> đã
viết:

**Comment by luongz** [comment]
befa389

added.
