### ISSUE TITLE
Links down

### ISSUE THREAD

**Issue by Animenosekai** [luongz/iptv-jp#27]
Hey !

Just to tell you that the links seem down

<img width="592" alt="Screenshot 0005-06-19 at 00 30 09" src="https://github.com/luongz/iptv-jp/assets/40539549/3e311b9a-5a52-4ada-adde-f37eff59da44">

**Comment by luongz** [comment]
![Screenshot_20230619-093202](https://github.com/luongz/iptv-jp/assets/76716526/c8cbcf5d-9d8a-423c-a7f0-e19ece2bd6ca)

fixed!

**Comment by Animenosekai** [comment]
It works great thanks !
