### ISSUE TITLE
Channels are crashing sometimes

### ISSUE THREAD

**Issue by junhit-coder** [luongz/iptv-jp#28]
Hi, I’m from Brazil, the channels are crashing sometimes, when im watching and my internet have a good connection. I’m using SS IPTV on my smart TV. Thanks!!! sorry for my bad English. My grandpa adores a lot watch Japanese channels.

**Comment by luongz** [comment]
Don't watch the v2 channel. v1 channel are working as well
Vào Th 5, 29 thg 6, 2023 lúc 22:31 junhit-coder ***@***.***>
đã viết:

**Comment by junhit-coder** [comment]
v1 channels, you say, a channels with HD in the title? For example: TV Tokyo HD.

**Comment by junhit-coder** [comment]
v1 Channels, you say, a channels with HD in the title? For example: Tv Tokyo HD. Because the are other TV Tokyo without HD in the title.> Don't watch the v2 channel. v1 channel are working as well

**Comment by luongz** [comment]
v2 is broken now. We are fixing it.
 > v1 Channels, you say, a channels with HD in the title?

Yes , In v1 , HD channel you get 720p res , without HD : 540p

**Comment by junhit-coder** [comment]
Currently, I was watching the channels with HD, but sometimes crash while I'm watching,pauses or comes back after a few seconds, and it happen frequently

**Comment by luongz** [comment]
> Currently, I was watching the channels with HD, but sometimes crash while I'm watching,pauses or comes back after a few seconds, and it happen frequently

I don't have these problems. May be check your internet connection or player issue,...

**Comment by junhit-coder** [comment]
Ok, thanks for help me, I will verify here.

**Comment by johnr9816** [comment]
I have the same issue. V1 will play for a few moments, and then stop. Using VLC it will eventually start playing again, however, only for a few moments before having to rebuffer. Internet connection is good. However, I noticed ping times to that server are long. 245ms to the server delivering the content. Meanwhile, only 5-6ms to google, and 3-4ms to bing. I am in the US on the east coast using a fiber connection with 200Mbps up and down. 

![image](https://github.com/luongz/iptv-jp/assets/18361411/07bb3a3d-9a18-49a4-b456-ac25b83fedc1)

Pinging google.jp only sees ping times increase to 7ms

![image](https://github.com/luongz/iptv-jp/assets/18361411/eefed2bc-ed4e-4fa3-9230-8e3296f389d7)

**Comment by vthanhtivi** [comment]
I'm the owner of the server "vthanhtivi.pw". 
The reason why the ping is so high is because i have the server in vietnam, but the connection from here to abroad is a bit unstable and slow, due to the audience connecting from abroad will be somewhat laggy and slower. 
I'm sorry that the viewing experience of the audience is not good, so in the near future I will proceed to add a new server to better serve the audience from abroad. 
Thanks for reading.
