### ISSUE TITLE
links are down or having an error

### ISSUE THREAD

**Issue by Johelectrix09** [luongz/iptv-jp#29]
Hello and good day can I ask what estimate day or month do you think v2 channels will be online just asking and I still appreciate your content ☺☺

**Comment by luongz** [comment]
v2 is ready , just waiting EPG assignment.

**Comment by Johelectrix09** [comment]
What happened sir did you have any server error??

**Comment by Johelectrix09** [comment]
Yesterday was actually ok what happened??

**Comment by Johelectrix09** [comment]
![Uploading Screenshot_2023-07-05-15-20-33-58_4aed3257f278fcf7bfa3abd644e23333.jpg…]()

**Comment by Johelectrix09** [comment]
hmm ok how sad thanks for the clarification

**Comment by luongz** [comment]
Fixed. The token automatically changed in GMT +7 00:00 , so i need to write some code.

**Comment by Johelectrix09** [comment]
I think most likely I need to watch on v1 sir v2 again has the token automatically changed again

**Comment by Johelectrix09** [comment]
The V2 channels are down again I think
