### ISSUE TITLE
NHK G HD wrong

### ISSUE THREAD

**Issue by xjz-01** [luongz/iptv-jp#31]
hello person in charge
Now in the high-definition streaming of nhk's comprehensive channel, the content cannot be shown, only this prompt.
![Screenshot_20230705-191724_Chrome](https://github.com/luongz/iptv-jp/assets/108247120/950686d6-b55f-476e-9916-a60c6494d214)

**Comment by luongz** [comment]
real source issue 
in this case match with the question in "QnA" : "Turn off the subtitles"

**Comment by luongz** [comment]
non-HD work well , you can watch
