### ISSUE TITLE
All streams down 

### ISSUE THREAD

**Issue by johnr9816** [luongz/iptv-jp#33]
All streams fail to play. 
V1's continuously retry and never start playing.

V2's return message in the playlist reads, "Sorry, the token is expired. Please continue watch on my IPTV playlist for best experience."

 
![image](https://github.com/luongz/iptv-jp/assets/18361411/00caf6d7-8795-4a6c-a725-715fdfcf7da5)

This is using the most up-to-date version from this morning. It was working fine until around 12:30 PM Eastern time. 
V1s were good until between 1:30 PM and 2:00 PM Eastern time.

**Comment by Prowindows62** [comment]
i've experiencing the same problem

**Comment by Johelectrix09** [comment]
It was actually a problem yesterday so yes the token automatically changed so they might need change up the code again

**Comment by luongz** [comment]
Please update the list and test. Thanks
