### ISSUE TITLE
Incorrectly formatted links

### ISSUE THREAD

**Issue by gabe56f** [luongz/iptv-jp#40]
Hi, first of all thank you for this amazing service, really glad someone's out there doing this

I wanted to reencode the streams a bit using ffmpeg, and sadly, due to an error in the formatting of the urls inside of the .m3u8 files, I can't seem to do so. (This is present both on ffmpeg 6.0 and 4.4)

All of the domains include a `:` after the domain name, prompting ffmpeg to look for a port, however it can't find one and thus won't open the .ts files.

(for instance, `https://domain.com:/live/whatever/1690336288966.ts`)

Can you please look into this, much appreciated.

**Comment by luongz** [comment]
Just remove the `:` ?

**Comment by gabe56f** [comment]
I can't since when I request the .m3u8 files, their contents change and they all have that `:` in them

Let's say, I have the whole playlist, and I want to download just one channels content with ffmpeg.
I'd do `ffmpeg -i https://sv92102.vthanhtivi.pw/jptv/213/117.m3u8 out.mp4` (or any other link for that matter)
however I can't do that because inside of said link, all of the urls linking to the .ts files contain that `:` in them

Like this one:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:23415
#EXT-X-TARGETDURATION:6
#EXTINF:4.987, no desc
https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340985251.ts
#EXTINF:4.996, no desc
https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340990550.ts
#EXTINF:4.002, no desc
https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340995429.ts
#EXTINF:4.991, no desc
https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340999224.ts
#EXTINF:4.999, no desc
https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690341004459.ts
```

**Comment by luongz** [comment]
> I can't since when I request the .m3u8 files, their contents change and they all have that `:` in them
> 
> Let's say, I have the whole playlist, and I want to download just one channels content with ffmpeg. I'd do `ffmpeg -i https://sv92102.vthanhtivi.pw/jptv/213/117.m3u8 out.mp4` (or any other link for that matter) however I can't do that because inside of said link, all of the urls linking to the .ts files contain that `:` in them
> 
> Like this one:
> 
> ```
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-MEDIA-SEQUENCE:23415
> #EXT-X-TARGETDURATION:6
> #EXTINF:4.987, no desc
> https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340985251.ts
> #EXTINF:4.996, no desc
> https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340990550.ts
> #EXTINF:4.002, no desc
> https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340995429.ts
> #EXTINF:4.991, no desc
> https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690340999224.ts
> #EXTINF:4.999, no desc
> https://jk-live-us76.supportnettv.com:/live/kanto_nhk_g_720/1690341004459.ts
> ```

We have no control over those links. As I say in Q&A, if you request our links , its redirect you to the links that host the channel.

**Comment by luongz** [comment]
Hey , can you try again?

**Comment by gabe56f** [comment]
It's working now, thank you so much <3
