### ISSUE TITLE
Merge the two EPG files

### ISSUE THREAD

**Issue by apommel** [luongz/iptv-jp#41]
First of all thank you for your very high quality work on this, that's a truly valuable resource.

I wanted to know if that would be feasible for you to merge the two EPG XML files linked in the m3u as only one XML? It seems like my player does not support more than one EPG files.

If you have no control over the EPG I would also understand.

**Comment by luongz** [comment]
I have control over the EPG host but I tried many times to merge 2 regions to 1 but failed.
I will find a solution to the EPG soon.
