### ISSUE TITLE
I'm having issues with some channels

### ISSUE THREAD

**Issue by NyanCat6886** [luongz/iptv-jp#47]
Many channels of the playlist (e.g: NTV or TV Tokyo) fail to open when I try to play them with VLC or Kodi, in my case VLC shows an error like it cannot connect to the url.
![unable to open MRL](https://github.com/luongz/iptv-jp/assets/68400794/4f6eb78c-8e8a-463a-8a27-5723902731e2)

**Comment by luongz** [comment]
fixed
