### ISSUE TITLE
The channel cannot be viewed

### ISSUE THREAD

**Issue by kdhh357** [luongz/iptv-jp#49]
The channel of http://asia.vthanhtivi server cannot be viewed.

**Comment by NyanCat6886** [comment]
Same here with many other channels like Tokyo MX

**Comment by luongz** [comment]
I dont have a PC now so i can't upload new links :c

Vào Th 2, 25 thg 12, 2023 lúc 20:06 kdhh357 ***@***.***> đã
viết:

**Comment by luongz** [comment]
Fixed
