### ISSUE TITLE
No streams are working at the moment

### ISSUE THREAD

**Issue by bigloubeats** [luongz/iptv-jp#50]
Unfortunately all streams are down

**Comment by bigloubeats** [comment]
Never mind! They’re back!

**Comment by bigloubeats** [comment]
Some are back but not all

**Comment by Shihaix** [comment]
AT-X down maybe can update link provider

**Comment by kdhh357** [comment]
I can’t even watch the video at the beginning of http://jp.vthanhnetwork.com
