### ISSUE TITLE
Stream not working

### ISSUE THREAD

**Issue by nazonomi** [luongz/iptv-jp#52]
・NHK G No Delay
・NHK G No Delay 2
・TVS

I would like you to fix it.

**Comment by luongz** [comment]
TVS no one watched it , both NHK channels I hosted to people get latest news of Noto Peninsula earthquakes , now it's not necessary now. And my server is not good too.
Rejected.

**Comment by nazonomi** [comment]
I understand. 
I hope you continue to do this as I love watching local TV. 
Hope you find a new server soon.
