### ISSUE TITLE
 BS11 HD (Test) are down

### ISSUE THREAD

**Issue by Moscow1991** [luongz/iptv-jp#53]
First of all, thank you for your efforts to maintain the channel. Now there is a channel BS11 HD (Test) that has stopped working. This channel is much more stable than vthanhtivi's BS11. Is it still possible to recover?Thank you

**Comment by luongz** [comment]
BS11 is up now. Maybe down sometime.

**Comment by luongz** [comment]
I have asked Thanh to fix the vthanhtivi links too. Just wait.
