### ISSUE TITLE
BS11 HD (Test) are down

### ISSUE THREAD

**Issue by Moscow1991** [luongz/iptv-jp#55]
The channel BS11 HD (Test) that has stopped working.

**Comment by luongz** [comment]
Sorry but i will fix it wwhen i have free time , right now i can't.

**Comment by Moscow1991** [comment]
Thanks for your work

**Comment by Moscow1991** [comment]
Now BS11 HD (Test) and AT-X (Test) that has stopped working.

**Comment by NHKRoku** [comment]
TVQ and TVS is also down

**Comment by luongz** [comment]
Test hosts are suspended. I will move to new hosts soon.
