### ISSUE TITLE
AT-X, BS11,and the channels in Tokyo are down

### ISSUE THREAD

**Issue by Hau45** [luongz/iptv-jp#58]
![Screenshot_20240327_111029](https://github.com/luongz/iptv-jp/assets/150981926/876ff432-d57d-4753-a640-dc3454f40dac)
Not only AT-X and BS11, but also the channels in the following picture are down. They are perhaps HD channels. Please fix them.
Thank you for maintaining the channel.

**Comment by luongz** [comment]
> ![Screenshot_20240327_111029](https://private-user-images.githubusercontent.com/150981926/317111531-876ff432-d57d-4753-a640-dc3454f40dac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTAxMDUsIm5iZiI6MTcxMTUwOTgwNSwicGF0aCI6Ii8xNTA5ODE5MjYvMzE3MTExNTMxLTg3NmZmNDMyLWQ1N2QtNDc1My1hNjQwLWRjMzQ1NGY0MGRhYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwMzIzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTIzOWYyZmQ3OTZkMjM1ODA0MTY5NzU5ODk4NWY2OTk3NzA3ODMyZjU0NzA0MWNhMzliMTc2MzNjNzliNTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B2cyASAzulnlryvShw36on_ROiS0JT7B4QOOr9QC870) Not only AT-X and BS11, but also the channels in the following picture are down. They are perhaps HD channels. Please fix them. Thank you for maintaining the channel.

I think those channels are geo-ip blocked. Still working in Vietnam.

**Comment by Hau45** [comment]
Okay, that makes sense.
I'll try using ip in Vietnam.

**Comment by vthanhtivi** [comment]
fixed
