### ISSUE TITLE
EPG channels seem to be wrong.

### ISSUE THREAD

**Issue by williamsonlogan** [luongz/iptv-jp#74]
It appears that the EPG for Animax is actually displaying the schedule for JSPORTS2, JSPORTS1 is showing the schedule for JSPORTS3, JSPORTS2 is showing JSPORTS4. And JSPORTS4 is showing wowowplus. And Green Channel is showing the schedule for JSPORTS1. These are just the ones I’ve been able to find by comparing what I’m getting from the EPG in the m3u file to publically available Japanese program schedules. Certain other ones such as TV asahi and Fuji TV are correct. Not sure if the EPG falls in the bounds of this project but wanted to bring attention to it.

**Comment by Moscow1991** [comment]
BS11 and AT-X EPG are also wrong

**Comment by luongz** [comment]
noted , will look into it.

**Comment by williamsonlogan** [comment]
I went through checking mine to use an alternate EPG source in the mean time, the issue largely seems to be the BS channels. All the other categories seem to be working fine but BS channels in particular are mixed around.

**Comment by luongz** [comment]
Temporary EPG for BS/CS: https://epg.djtmewibu.com/jcom.xml

Due to a change of channel ids, the grabber is not working normally for the main EPG.
I will fix and re-add it when done.

**Comment by luongz** [comment]
my host broken rn so i use another epg source. Closed

**Comment by weldon1045** [comment]
Why don't you consider using this source?

http://webgrabplus.com/epg-channels#stc_27
