### ISSUE TITLE
Some Tokyo, BS and CS channels are currently down.

### ISSUE THREAD

**Issue by cam4076056** [luongz/iptv-jp#75]
At the time of writing, the channels currently down are:

- NHK G
- NHK E
- NTV
- TBS
- Fuji TV
- TV Asahi
- TV Tokyo
- Tokyo MX1
- NHK BS
- BS11
- Animax
- WOWOW Prime (nekocdn)
- AT-X
- MTV
- Space Shower TV (n3ko)

All of these return "Error 404" when trying to open or play them.

**Comment by vthanhtivi** [comment]
my package is expired. pls wait
