### ISSUE TITLE
Neetball change from AT-X to BS11

### ISSUE THREAD

**Issue by cam4076056** [luongz/iptv-jp#78]
It seems neetball3 changed the channel from AT-X to BS11 today.

**Comment by luongz** [comment]
I don't have a PC rn so i cant do any fix to the list.
Hope someone can PR.

Vào CN, 21 thg 7, 2024 lúc 22:14 cam4076056 ***@***.***> đã
viết:

**Comment by cam4076056** [comment]
Pull Request proposed:
https://github.com/luongz/iptv-jp/pull/79

**Comment by luongz** [comment]
Thanks you.
