### ISSUE TITLE
channels down

### ISSUE THREAD

**Issue by carmagnolle** [luongz/iptv-jp#81]
NHK G/E, NTV, TBS, Fuji TV, TV Asahi, TV Tokyo, Tokyo MX 1 are down, when you have time could you look into it?

And thanks a bunch!! I watch a lot of TBS and NHK G.

**Comment by weldon1045** [comment]
It is more than likely @vthanhtivi package has expired.

By the way, haven't you considered adding willfonk source to the main list?

**Comment by luongz** [comment]
> It is more than likely @vthanhtivi package has expired.

It seems our host expired. Need to wait for a response from him.

> By the way, haven't you considered adding willfonk source to the main list?

The owner of the Willfonk links has contacted me to take down their links before.

**Comment by vthanhtivi** [comment]
fixed. original server was timeout
