### ISSUE TITLE
Remove unnecessary space at beginning of titles

### ISSUE THREAD

**Issue by tsr** [luongz/iptv-jp#90]
Please remove the unnecessary space at beginning of titles, as it makes sorting in various applications with additional channels complicated.

E.g.:

`#EXTINF:-1 group-title="Tokyo" tvg-id="nhkg_tokyo" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/6/6f/NHK%E7%B7%8F%E5%90%88%E3%83%AD%E3%82%B42020-.png", NHK G`

should be:

`#EXTINF:-1 group-title="Tokyo" tvg-id="nhkg_tokyo" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/6/6f/NHK%E7%B7%8F%E5%90%88%E3%83%AD%E3%82%B42020-.png",NHK G`

Notice the removed space between the , and N.

Thank you very much!

**Comment by luongz** [comment]
Can you explain: "it makes sorting in various applications with additional channels complicated"?

**Comment by weldon1045** [comment]
Probably they mean sorting from A-Z is complicated due to the space before the channel title being present.

I don't know which client are they using and which other clients may have the same problem.
