### ISSUE TITLE
Check source down

### ISSUE THREAD

**Issue by NHKRoku** [luongz/iptv-jp#97]
Can you check the available of the following test channel:
nhkG,TVS
Thank you

**Comment by luongz** [comment]
There is no signal of TVS right now.
I have manually restored the NHK G signal, please try again.

**Comment by dm-25** [comment]
以前あったテストチャンネルチバテレとテレ玉は、どうなってますか？

**Comment by weldon1045** [comment]
By the way, luongz, it seems some vthanh channels from Tokyo are returning error 404 for some reason, and I think the problem persists with some BS and CS channels as well.

**Comment by luongz** [comment]
> テストチャンネルにあったtvhは、どんな状況なんですか？

> 以前あったテストチャンネルチバテレとテレ玉は、どうなってますか？

Can you stop asking about the test channels I have explained before?

**Comment by luongz** [comment]
> By the way, luongz, it seems some vthanh channels from Tokyo are returning error 404 for some reason, and I think the problem persists with some BS and CS channels as well.

Still working for me.

Can you open those links? Both are NHK G
https://vnpt.nekocdn.xyz/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8
https://vnpt.nekocdn.xyz/memfs/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8

**Comment by weldon1045** [comment]
> > By the way, luongz, it seems some vthanh channels from Tokyo are returning error 404 for some reason, and I think the problem persists with some BS and CS channels as well.
> 
> Still working for me.
> 
> Can you open those links? Both are NHK G https://vnpt.nekocdn.xyz/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8 https://vnpt.nekocdn.xyz/memfs/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8

First one opens without problems, the second one returns error 404.

**Comment by luongz** [comment]
> > > By the way, luongz, it seems some vthanh channels from Tokyo are returning error 404 for some reason, and I think the problem persists with some BS and CS channels as well.
> > 
> > 
> > Still working for me.
> > Can you open those links? Both are NHK G https://vnpt.nekocdn.xyz/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8 https://vnpt.nekocdn.xyz/memfs/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8
> 
> First one opens without problems, the second one returns error 404.

Can you list the channels where you have faced errors?

**Comment by weldon1045** [comment]
> > > > By the way, luongz, it seems some vthanh channels from Tokyo are returning error 404 for some reason, and I think the problem persists with some BS and CS channels as well.
> > > 
> > > 
> > > Still working for me.
> > > Can you open those links? Both are NHK G https://vnpt.nekocdn.xyz/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8 https://vnpt.nekocdn.xyz/memfs/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8
> > 
> > 
> > First one opens without problems, the second one returns error 404.
> 
> Can you list the channels where you have faced errors?

NHK G, NHK E, NTV, TV Asahi, NHK BS, Wowow Prime, Space Shower TV

**Comment by luongz** [comment]
> > > > > By the way, luongz, it seems some vthanh channels from Tokyo are returning error 404 for some reason, and I think the problem persists with some BS and CS channels as well.
> > > > 
> > > > 
> > > > Still working for me.
> > > > Can you open those links? Both are NHK G https://vnpt.nekocdn.xyz/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8 https://vnpt.nekocdn.xyz/memfs/b783a989-9e73-4bce-bfa3-9996a9eaa455.m3u8
> > > 
> > > 
> > > First one opens without problems, the second one returns error 404.
> > 
> > 
> > Can you list the channels where you have faced errors?
> 
> NHK G, NHK E, NTV, TV Asahi, NHK BS, Wowow Prime, Space Shower TV

Working on my side, are you currently using the latest list?

**Comment by weldon1045** [comment]
Updated to the latest list. It seems there are no more issues.

**Comment by dm-25** [comment]
以下のテストチャンネルが利用可能か確認願います。tokyo mx1 tokyomx2

**Comment by dm-25** [comment]
tokyo mx2の受信状況は、どんな状況なんですか？
