### ISSUE TITLE
Vthanh channels down

### ISSUE THREAD

**Issue by weldon1045** [luongz/iptv-jp#98]
All channels in Tokyo, BS and CS are currently down.

**Comment by luongz** [comment]
The Vthanh server is temporarily down due to a power outage caused by a
typhoon. It will take a long time to recover, so temporarily you can watch
the 540p channels until it's back.


Vào CN, 8 thg 9, 2024 lúc 03:05 weldon1045 ***@***.***> đã
viết:

**Comment by dm-25** [comment]
tssの現在の状況を教えてください

**Comment by dm-25** [comment]
テストチャンネルから正式なチャンネルに昇格する事は有りますか？

**Comment by luongz** [comment]
Fixed.
